# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a3583baf6936418568c40051e324750dfcb885f242c63b8a33c77fd17c69cf508cf69202fd78490f9a2b074e456dbdecbb9c9b23dcbed237fcbc049e97161a

test:
  secret_key_base: 363d46a7a0e780f6efafdcd84fac7cf6b15d796cf8aea3f03c414814fb6df050e985db8f5eb64c89e8875d07da35bfa34bd6c816e72b400e597fe6a9af378499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
